<a href="https://colab.research.google.com/github/mateus-neres/projeto_de_analise_estatistica_enem_2019/blob/main/probabilidade_etapa06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
import pandas as pd
import numpy as np

In [85]:
enem_sp = pd.read_csv("/content/drive/MyDrive/curso_Udemy/curso_estatistica_python/enem_2019_tratado.csv",
                      sep=",", encoding="iso-8859-1")

In [86]:
# Exibir todas as colunas sem abreviações
pd.set_option("display.max_columns", None)

In [87]:
enem_guarulhos = enem_sp.loc[enem_sp.MUNICIPIO_RESIDENCIA == "Guarulhos"]

In [88]:
enem_bauru = enem_sp.loc[enem_sp.MUNICIPIO_RESIDENCIA == "Bauru"]

In [89]:
enem_guarulhos.head()

,INSCRICAO,MUNICIPIO_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,RACA,NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,NO_MUNICIPIO_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
4,"1,90E+11",Guarulhos,23,F,1,branca,1,1,não_respondeu,NaN,NaN,1,1,1,1,625.7,646.5,629.3,796.1,inglês,1.0,160.0,200.0,180.0,180.0,160.0,880.0,sim
56,"1,90E+11",Guarulhos,17,F,1,parda,1,2,pública,NaN,NaN,1,1,1,1,373.4,511.2,515.7,468.1,espanhol,1.0,100.0,60.0,60.0,100.0,0.0,320.0,sim
69,"1,90E+11",Guarulhos,27,M,1,não_declarado,1,1,não_respondeu,NaN,NaN,1,1,1,1,55.8,58.7,620.5,743.8,inglês,1.0,120.0,180.0,120.0,120.0,160.0,700.0,sim
130,"1,90E+11",Guarulhos,28,F,1,branca,1,1,não_respondeu,NaN,NaN,1,1,1,1,517.2,57.1,584.5,415.1,inglês,1.0,160.0,120.0,160.0,120.0,100.0,660.0,sim
202,"1,90E+11",Guarulhos,17,F,1,parda,1,2,pública,35005824.0,Guarulhos,1,1,1,1,490.4,541.1,556.3,594.9,inglês,1.0,120.0,120.0,120.0,120.0,160.0,640.0,sim

In [90]:
enem_bauru.head()

,INSCRICAO,MUNICIPIO_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,RACA,NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,NO_MUNICIPIO_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
477,"1,90E+11",Bauru,21,M,1,branca,1,1,não_respondeu,NaN,NaN,1,1,1,1,537.6,587.4,582.9,664.1,inglês,1.0,100.0,120.0,120.0,120.0,100.0,560.0,sim
928,"1,90E+11",Bauru,17,M,1,amarela,1,2,pública,35025240.0,Bauru,1,1,1,1,620.4,583.9,552.5,740.3,inglês,1.0,140.0,120.0,120.0,140.0,100.0,620.0,sim
1070,"1,90E+11",Bauru,19,M,1,branca,1,1,não_respondeu,NaN,NaN,1,1,1,1,599.7,711.5,69.2,789.2,inglês,1.0,160.0,200.0,200.0,200.0,200.0,960.0,sim
1235,"1,90E+11",Bauru,18,F,1,parda,1,2,privada,35115435.0,Bauru,1,1,1,1,560.7,647.8,610.5,71.5,inglês,1.0,140.0,140.0,140.0,140.0,120.0,680.0,sim
1506,"1,90E+11",Bauru,19,M,1,branca,1,1,não_respondeu,NaN,NaN,1,1,1,1,499.3,567.5,557.2,533.8,espanhol,1.0,120.0,140.0,120.0,100.0,140.0,620.0,sim

In [91]:
len(enem_guarulhos)

15647

In [92]:
len(enem_bauru)

4171

##Função de probabilidade de ocorrer um evento

In [93]:
def probab (A,E):
  resultado = (A / E)*100
  print(f"{resultado:.2f}")

In [94]:
probab(len(enem_guarulhos), len(enem_sp))

3.13

In [95]:
probab(len(enem_bauru), len(enem_sp))

0.83

##Probabilidade de não ocorrer um evento

In [96]:
def n_probab(A, B):
  resultado = (1 - (A / B)) * 100
  print(f"{resultado:.2f}")

In [97]:
n_probab(len(enem_bauru), len(enem_sp))

99.17

In [98]:
n_probab(len(enem_guarulhos), len(enem_sp))

96.87

##Probabilidade da união do multamente exclusivos(A U B)

In [99]:
# CRIANDO A FUNÇÃO PROBABILIDADE DA UNIÃO MUTUAMENTE EXCLUSIVOS (AUB)
def probab_uniao (A,B,E):
  resultado = (A/E + B/E) * 100
  print(f"{resultado:.2f}")

In [100]:
probab_uniao(len(enem_guarulhos), len(enem_bauru), len(enem_sp))

3.96

##Probabilidade da intersecção de eventos

In [101]:
# cRIANDO A FUNÇÃO PROBABILIDADE DA INTERSECÇÃO DE EVENTOS
def probab_intersec (A, B, E):
  produto = (A/E * B/E)*100
  print(f"{produto:.3f}")

In [102]:
# PROBABILIDADE DE RETIRAR UM VESTIBULANDO DE GUARULHOS E BAURO (COM REPOSIÇÃO)
probab_intersec(len(enem_guarulhos), len(enem_bauru), len(enem_sp))

0.026

##Probabilidade condicional

In [103]:
def probab_cond (AB,B):
  condicional = (AB / B)* 100
  print(f"{condicional:.2f}")

In [104]:
mulher = enem_sp.loc[enem_sp.SEXO == "F"]

In [105]:
mulher_parda = mulher.loc[mulher.RACA == "parda"]

In [106]:
display(mulher_parda)

,INSCRICAO,MUNICIPIO_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,RACA,NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,NO_MUNICIPIO_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
1,"1,90E+11",São Paulo,17,F,1,parda,1,2,privada,15567761.0,Belém,1,1,1,1,576.2,641.1,634.3,731.8,inglês,1.0,160.0,120.0,200.0,200.0,200.0,880.0,não
3,"1,90E+11",Embu-Guaçu,17,F,1,parda,1,2,pública,NaN,NaN,1,1,1,1,399.6,426.8,487.2,419.2,inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,sim
7,"1,90E+11",Santo André,20,F,1,parda,1,1,não_respondeu,NaN,NaN,1,1,1,1,446.2,521.8,517.7,508.5,espanhol,1.0,120.0,120.0,120.0,100.0,80.0,540.0,sim
9,"1,90E+11",Santo André,44,F,2,parda,1,1,não_respondeu,NaN,NaN,1,1,1,1,507.4,56.0,529.7,488.1,espanhol,1.0,120.0,120.0,120.0,120.0,40.0,520.0,sim
11,"1,90E+11",Guará,17,F,1,parda,1,2,pública,35023310.0,Guará,1,1,1,1,499.1,540.3,549.2,535.1,inglês,1.0,140.0,120.0,140.0,160.0,120.0,680.0,sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499932,"1,90E+11",Santa Bárbara d'Oeste,18,F,1,parda,1,1,não_respondeu,NaN,NaN,1,1,1,1,506.5,587.2,553.8,52.1,inglês,1.0,140.0,120.0,180.0,160.0,180.0,780.0,não
499933,"1,90E+11",Pardinho,17,F,0,parda,1,2,pública,NaN,NaN,1,1,1,1,535.6,43.6,566.9,534.7,inglês,1.0,140.0,120.0,120.0,120.0,160.0,660.0,sim
499934,"1,90E+11",São Paulo,20,F,1,parda,1,1,não_respondeu,NaN,NaN,1,1,1,1,55.9,527.4,524.6,514.8,espanhol,1.0,100.0,120.0,120.0,140.0,140.0,620.0,sim
499935,"1,90E+11",São Paulo,18,F,1,parda,1,1,não_respondeu,NaN,NaN,1,1,1,1,417.8,394.3,52.7,479.1,espanhol,1.0,100.0,120.0,120.0,140.0,100.0,580.0,sim
499937,"1,90E+11",São Paulo,17,F,1,parda,1,2,pública,35001156.0,São Paulo,1,1,1,1,398.6,468.3,483.9,487.3,inglês,1.0,120.0,80.0,60.0,120.0,0.0,380.0,sim

In [108]:
probab_cond(len(mulher_parda), len(mulher))

30.76