<a href="https://colab.research.google.com/github/mateus-neres/tratamento_enem_2019/blob/main/tratamento_enem_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**PROJETO DE ANÁLISE ESTATISTICA ENEM 2019**

Este projeto analise os resultados do ENEM no estado de São Paulo no ano de 2019.

Os dados foram extraídos do site do INEP:

http://inep.gov.br/mocrodados

In [187]:
import numpy as np
import pandas as pd

In [188]:
dados = pd.read_csv("/content/drive/MyDrive/curso_Udemy/curso_estatistica_python/microdados_enem_2019_sp.csv", sep=";", encoding="iso-8859-1" )
# encoding: codificação de caracteres, normalmente ultiza-se o "iso-8859-1", utf-8, latin-1

#**Destrucando colunas**

Exibi todas as linhas e colunas sem ocutações ou abreviações

In [189]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

#**Estração e limpesa dos dados**

In [190]:
dados.head()

,NU_INSCRICAO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,CO_MUNICIPIO_NASCIMENTO,NO_MUNICIPIO_NASCIMENTO,CO_UF_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q025
0,"1,90E+11",3546801,Santa Isabel,35,SP,22,M,1,3,1,1506500.0,Santa Izabel do Pará,15.0,PA,1,4,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,5646.0,5858.0,5929.0,6002.0,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",3538204,Pinhalzinho,35,SP,19,M,1,3,1,1503804.0,Jacundá,15.0,PA,1,2,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",3550308,São Paulo,35,SP,17,F,1,3,1,1501402.0,Belém,15.0,PA,2,0,3,1.0,0,15567761.0,1501402.0,Belém,15.0,PA,4.0,1.0,1.0,1,1,1,1,5762.0,6411.0,6343.0,7318.0,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",3548708,São Bernardo do Campo,35,SP,19,M,1,3,1,3548708.0,São Bernardo do Campo,35.0,SP,2,0,2,1.0,0,35904958.0,3548708.0,São Bernardo do Campo,35.0,SP,2.0,1.0,1.0,1,1,1,1,4022.0,4248.0,5096.0,3932.0,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",3549409,São Joaquim da Barra,35,SP,37,M,2,1,1,3549409.0,São Joaquim da Barra,35.0,SP,1,3,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

In [191]:
#O número total de inscrito em são Paulo foi de 813772, sendo de 15,97% de todo o Brasil que foi de 50955308 inscritos
dados.shape # vai passar (813772, 44) -> (linhas, registros ou atributos)

(813772, 44)

In [192]:
#Ánalise dos tipos de atributos
#Object: string
#int64: inteiros
#float64: reais
#complex: complexos
dados.dtypes

NU_INSCRICAO                object
CO_MUNICIPIO_RESIDENCIA      int64
NO_MUNICIPIO_RESIDENCIA     object
CO_UF_RESIDENCIA             int64
SG_UF_RESIDENCIA            object
NU_IDADE                     int64
TP_SEXO                     object
TP_ESTADO_CIVIL              int64
TP_COR_RACA                  int64
TP_NACIONALIDADE             int64
CO_MUNICIPIO_NASCIMENTO    float64
NO_MUNICIPIO_NASCIMENTO     object
CO_UF_NASCIMENTO           float64
SG_UF_NASCIMENTO            object
TP_ST_CONCLUSAO              int64
TP_ANO_CONCLUIU              int64
TP_ESCOLA                    int64
TP_ENSINO                  float64
IN_TREINEIRO                 int64
CO_ESCOLA                  float64
CO_MUNICIPIO_ESC           float64
NO_MUNICIPIO_ESC            object
CO_UF_ESC                  float64
SG_UF_ESC                   object
TP_DEPENDENCIA_ADM_ESC     float64
TP_LOCALIZACAO_ESC         float64
TP_SIT_FUNC_ESC            float64
TP_PRESENCA_CN               int64
TP_PRESENCA_CH               int64
TP_PRESENCA_LC               int64
TP_PRESENCA_MT               int64
NU_NOTA_CN                 float64
NU_NOTA_CH                 float64
NU_NOTA_LC                 float64
NU_NOTA_MT                 float64
TP_LINGUA                    int64
TP_STATUS_REDACAO          float64
NU_NOTA_COMP1              float64
NU_NOTA_COMP2              float64
NU_NOTA_COMP3              float64
NU_NOTA_COMP4              float64
NU_NOTA_COMP5              float64
NU_NOTA_REDACAO            float64
Q025                        object
dtype: object

Removendo colunas desnecessárias

In [193]:
dados1 = dados.drop(columns=["CO_UF_RESIDENCIA","SG_UF_RESIDENCIA","CO_MUNICIPIO_NASCIMENTO","CO_MUNICIPIO_RESIDENCIA","NO_MUNICIPIO_NASCIMENTO","CO_UF_NASCIMENTO","SG_UF_NASCIMENTO","TP_ANO_CONCLUIU", "TP_ENSINO","CO_MUNICIPIO_ESC","CO_UF_ESC", "SG_UF_ESC","TP_DEPENDENCIA_ADM_ESC","TP_LOCALIZACAO_ESC","TP_SIT_FUNC_ESC"], )

In [194]:
dados1.head()

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ESCOLA,IN_TREINEIRO,CO_ESCOLA,NO_MUNICIPIO_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q025
0,"1,90E+11",Santa Isabel,22,M,1,3,1,1,1,0,NaN,NaN,1,1,1,1,5646.0,5858.0,5929.0,6002.0,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",Pinhalzinho,19,M,1,3,1,1,1,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",São Paulo,17,F,1,3,1,2,3,0,15567761.0,Belém,1,1,1,1,5762.0,6411.0,6343.0,7318.0,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",São Bernardo do Campo,19,M,1,3,1,2,2,0,35904958.0,São Bernardo do Campo,1,1,1,1,4022.0,4248.0,5096.0,3932.0,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",São Joaquim da Barra,37,M,2,1,1,1,1,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

In [195]:
dados1.shape

(813772, 29)

#**Renomear varias colunas**

In [196]:
# Aplicando em apenas uma coluna
dados1 = dados1.rename(columns={"NU_NOTA_REDACAO":"NOTA_REDACAO"})

In [197]:
# Aplicando em varias colunas
dados1 = dados1.rename(columns={"NU_NOTA_CN":"NOTA_CN", "NU_NOTA_CH":"NOTA_CH",
                                "NU_NOTA_LC":"NOTA_LC", "NU_NOTA_MT":"NOTA_MT"})

In [198]:
dados1 = dados1.rename(columns={"NU_INSCRICAO":"INSCRICAO","NO_MUNICIPIO_RESIDENCIA":"MUNICIPIO_RESIDENCIA",
                                "NU_IDADE":"IDADE", "TP_SEXO":"SEXO","TP_ESTADO_CIVIL":"ESTADO_CIVIL",
                                "TP_COR_RACA":"RACA", "TP_NACIONALIDADE":"NACIONALIDADE","TP_ESCOLA":"ESCOLA","Q025":"INTERNET"})

In [199]:
dados1 = dados1.rename(columns={"NU_NOTA_COMP1":"COMP1","NU_NOTA_COMP2":"COMP2","NU_NOTA_COMP3":"COMP3","NU_NOTA_COMP4":"COMP4","NU_NOTA_COMP5	":"COMP5"})

In [200]:
dados1 = dados1.rename(columns={"TP_LINGUA":"LINGUA"})

In [201]:
dados1.head()

,INSCRICAO,MUNICIPIO_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,RACA,NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,IN_TREINEIRO,CO_ESCOLA,NO_MUNICIPIO_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,NU_NOTA_COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",Santa Isabel,22,M,1,3,1,1,1,0,NaN,NaN,1,1,1,1,5646.0,5858.0,5929.0,6002.0,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",Pinhalzinho,19,M,1,3,1,1,1,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",São Paulo,17,F,1,3,1,2,3,0,15567761.0,Belém,1,1,1,1,5762.0,6411.0,6343.0,7318.0,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",São Bernardo do Campo,19,M,1,3,1,2,2,0,35904958.0,São Bernardo do Campo,1,1,1,1,4022.0,4248.0,5096.0,3932.0,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",São Joaquim da Barra,37,M,2,1,1,1,1,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

#**Conrrigindo erro nas notas individuais**

In [202]:
dados1.loc[:,"NOTA_CN"] /= 10
dados1.loc[:,"NOTA_CH"] /= 10
dados1.loc[:,"NOTA_LC"] /= 10
dados1.loc[:,"NOTA_MT"] /= 10

In [203]:
display(dados1.head(5))

,INSCRICAO,MUNICIPIO_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,RACA,NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,IN_TREINEIRO,CO_ESCOLA,NO_MUNICIPIO_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,NU_NOTA_COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",Santa Isabel,22,M,1,3,1,1,1,0,NaN,NaN,1,1,1,1,564.6,585.8,592.9,600.2,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",Pinhalzinho,19,M,1,3,1,1,1,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",São Paulo,17,F,1,3,1,2,3,0,15567761.0,Belém,1,1,1,1,576.2,641.1,634.3,731.8,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",São Bernardo do Campo,19,M,1,3,1,2,2,0,35904958.0,São Bernardo do Campo,1,1,1,1,402.2,424.8,509.6,393.2,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",São Joaquim da Barra,37,M,2,1,1,1,1,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

##**Reanomear registros (linha)**

In [204]:
dados1["RACA"] = dados1["RACA"].replace({0:"não_declarado", 1:"branca", 2:"preta",3:"parda",4:"amarela",5:"indígena"})
dados1["INTERNET"] = dados1["INTERNET"].replace({"A":"não", "B":"sim"})
# Outra maneira de fazer:
# Exp: dados1["INTERNET"] = dados1["INTERNET"].replace(["A","B"], ["não","sim"])

In [205]:
dados1["ESCOLA"] = dados1["ESCOLA"].replace([1,2,3,4], ["não_respondeu","pública","privada","exterior"])

In [207]:
dados1["LINGUA"] = dados1["LINGUA"].replace([0,1],["inglês","espanhol"])

In [206]:
dados1.head()

,INSCRICAO,MUNICIPIO_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,RACA,NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,IN_TREINEIRO,CO_ESCOLA,NO_MUNICIPIO_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,NU_NOTA_COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",Santa Isabel,22,M,1,parda,1,1,não_respondeu,0,NaN,NaN,1,1,1,1,564.6,585.8,592.9,600.2,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,sim
1,"1,90E+11",Pinhalzinho,19,M,1,parda,1,1,não_respondeu,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,não
2,"1,90E+11",São Paulo,17,F,1,parda,1,2,privada,0,15567761.0,Belém,1,1,1,1,576.2,641.1,634.3,731.8,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,não
3,"1,90E+11",São Bernardo do Campo,19,M,1,parda,1,2,pública,0,35904958.0,São Bernardo do Campo,1,1,1,1,402.2,424.8,509.6,393.2,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,sim
4,"1,90E+11",São Joaquim da Barra,37,M,2,branca,1,1,não_respondeu,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sim