<a href="https://colab.research.google.com/github/mateus-neres/tratamento_enem_2019/blob/main/tratamento_enem_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**PROJETO DE ANÁLISE ESTATISTICA ENEM 2019**

Este projeto analisa os resultados do ENEM no estado de São Paulo no ano de 2019.

Os dados foram extraídos do site do INEP:

http://inep.gov.br/mocrodados

In [1]:
import numpy as np
import pandas as pd

In [2]:
dados = pd.read_csv("/content/drive/MyDrive/curso_Udemy/curso_estatistica_python/microdados_enem_2019_sp.csv", sep=";", encoding="iso-8859-1" )
# encoding: codificação de caracteres, normalmente ultiza-se o "iso-8859-1", utf-8, latin-1

#**Destrucando colunas**

Exibi todas as linhas e colunas sem ocutações ou abreviações

In [3]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

#**Estração e limpesa dos dados**

In [4]:
dados.head()

,NU_INSCRICAO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,CO_MUNICIPIO_NASCIMENTO,NO_MUNICIPIO_NASCIMENTO,CO_UF_NASCIMENTO,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q025
0,"1,90E+11",3546801,Santa Isabel,35,SP,22,M,1,3,1,1506500.0,Santa Izabel do Pará,15.0,PA,1,4,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,5646.0,5858.0,5929.0,6002.0,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",3538204,Pinhalzinho,35,SP,19,M,1,3,1,1503804.0,Jacundá,15.0,PA,1,2,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",3550308,São Paulo,35,SP,17,F,1,3,1,1501402.0,Belém,15.0,PA,2,0,3,1.0,0,15567761.0,1501402.0,Belém,15.0,PA,4.0,1.0,1.0,1,1,1,1,5762.0,6411.0,6343.0,7318.0,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",3548708,São Bernardo do Campo,35,SP,19,M,1,3,1,3548708.0,São Bernardo do Campo,35.0,SP,2,0,2,1.0,0,35904958.0,3548708.0,São Bernardo do Campo,35.0,SP,2.0,1.0,1.0,1,1,1,1,4022.0,4248.0,5096.0,3932.0,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",3549409,São Joaquim da Barra,35,SP,37,M,2,1,1,3549409.0,São Joaquim da Barra,35.0,SP,1,3,1,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

In [5]:
#O número total de inscrito em são Paulo foi de 813772, sendo de 15,97% de todo o Brasil que foi de 50955308 inscritos
dados.shape # vai passar (813772, 44) -> (linhas, registros ou atributos)

(813772, 44)

In [6]:
#Ánalise dos tipos de atributos
#Object: string
#int64: inteiros
#float64: reais
#complex: complexos
dados.dtypes

NU_INSCRICAO                object
CO_MUNICIPIO_RESIDENCIA      int64
NO_MUNICIPIO_RESIDENCIA     object
CO_UF_RESIDENCIA             int64
SG_UF_RESIDENCIA            object
NU_IDADE                     int64
TP_SEXO                     object
TP_ESTADO_CIVIL              int64
TP_COR_RACA                  int64
TP_NACIONALIDADE             int64
CO_MUNICIPIO_NASCIMENTO    float64
NO_MUNICIPIO_NASCIMENTO     object
CO_UF_NASCIMENTO           float64
SG_UF_NASCIMENTO            object
TP_ST_CONCLUSAO              int64
TP_ANO_CONCLUIU              int64
TP_ESCOLA                    int64
TP_ENSINO                  float64
IN_TREINEIRO                 int64
CO_ESCOLA                  float64
CO_MUNICIPIO_ESC           float64
NO_MUNICIPIO_ESC            object
CO_UF_ESC                  float64
SG_UF_ESC                   object
TP_DEPENDENCIA_ADM_ESC     float64
TP_LOCALIZACAO_ESC         float64
TP_SIT_FUNC_ESC            float64
TP_PRESENCA_CN               int64
TP_PRESENCA_CH               int64
TP_PRESENCA_LC               int64
TP_PRESENCA_MT               int64
NU_NOTA_CN                 float64
NU_NOTA_CH                 float64
NU_NOTA_LC                 float64
NU_NOTA_MT                 float64
TP_LINGUA                    int64
TP_STATUS_REDACAO          float64
NU_NOTA_COMP1              float64
NU_NOTA_COMP2              float64
NU_NOTA_COMP3              float64
NU_NOTA_COMP4              float64
NU_NOTA_COMP5              float64
NU_NOTA_REDACAO            float64
Q025                        object
dtype: object

Removendo colunas desnecessárias

In [7]:
dados1 = dados.drop(columns=["CO_UF_RESIDENCIA","SG_UF_RESIDENCIA","CO_MUNICIPIO_NASCIMENTO","CO_MUNICIPIO_RESIDENCIA","NO_MUNICIPIO_NASCIMENTO","CO_UF_NASCIMENTO","SG_UF_NASCIMENTO","TP_ANO_CONCLUIU", "TP_ENSINO","CO_MUNICIPIO_ESC","CO_UF_ESC", "SG_UF_ESC","TP_DEPENDENCIA_ADM_ESC","TP_LOCALIZACAO_ESC","TP_SIT_FUNC_ESC"], )

In [8]:
dados1.head()

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ESCOLA,IN_TREINEIRO,CO_ESCOLA,NO_MUNICIPIO_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q025
0,"1,90E+11",Santa Isabel,22,M,1,3,1,1,1,0,NaN,NaN,1,1,1,1,5646.0,5858.0,5929.0,6002.0,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",Pinhalzinho,19,M,1,3,1,1,1,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",São Paulo,17,F,1,3,1,2,3,0,15567761.0,Belém,1,1,1,1,5762.0,6411.0,6343.0,7318.0,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",São Bernardo do Campo,19,M,1,3,1,2,2,0,35904958.0,São Bernardo do Campo,1,1,1,1,4022.0,4248.0,5096.0,3932.0,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",São Joaquim da Barra,37,M,2,1,1,1,1,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

In [9]:
dados1.shape

(813772, 29)

#**Renomear varias colunas**

In [10]:
# Aplicando em apenas uma coluna
dados1 = dados1.rename(columns={"NU_NOTA_REDACAO":"NOTA_REDACAO"})

In [11]:
# Aplicando em varias colunas
dados1 = dados1.rename(columns={"NU_NOTA_CN":"NOTA_CN", "NU_NOTA_CH":"NOTA_CH",
                                "NU_NOTA_LC":"NOTA_LC", "NU_NOTA_MT":"NOTA_MT"})

In [12]:
dados1 = dados1.rename(columns={"NU_INSCRICAO":"INSCRICAO","NO_MUNICIPIO_RESIDENCIA":"MUNICIPIO_RESIDENCIA",
                                "NU_IDADE":"IDADE", "TP_SEXO":"SEXO","TP_ESTADO_CIVIL":"ESTADO_CIVIL",
                                "TP_COR_RACA":"RACA", "TP_NACIONALIDADE":"NACIONALIDADE","TP_ESCOLA":"ESCOLA","Q025":"INTERNET"})

In [13]:
dados1 = dados1.rename(columns={"NU_NOTA_COMP1":"COMP1","NU_NOTA_COMP2":"COMP2","NU_NOTA_COMP3":"COMP3","NU_NOTA_COMP4":"COMP4","NU_NOTA_COMP5":"COMP5"})

In [14]:
dados1 = dados1.rename(columns={"TP_LINGUA":"LINGUA"})

In [15]:
dados1.head()

,INSCRICAO,MUNICIPIO_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,RACA,NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,IN_TREINEIRO,CO_ESCOLA,NO_MUNICIPIO_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",Santa Isabel,22,M,1,3,1,1,1,0,NaN,NaN,1,1,1,1,5646.0,5858.0,5929.0,6002.0,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",Pinhalzinho,19,M,1,3,1,1,1,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",São Paulo,17,F,1,3,1,2,3,0,15567761.0,Belém,1,1,1,1,5762.0,6411.0,6343.0,7318.0,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",São Bernardo do Campo,19,M,1,3,1,2,2,0,35904958.0,São Bernardo do Campo,1,1,1,1,4022.0,4248.0,5096.0,3932.0,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",São Joaquim da Barra,37,M,2,1,1,1,1,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

#**Conrrigindo erro nas notas individuais**

In [16]:
dados1.loc[:,"NOTA_CN"] /= 10
dados1.loc[:,"NOTA_CH"] /= 10
dados1.loc[:,"NOTA_LC"] /= 10
dados1.loc[:,"NOTA_MT"] /= 10

In [17]:
display(dados1.head(5))

,INSCRICAO,MUNICIPIO_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,RACA,NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,IN_TREINEIRO,CO_ESCOLA,NO_MUNICIPIO_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",Santa Isabel,22,M,1,3,1,1,1,0,NaN,NaN,1,1,1,1,564.6,585.8,592.9,600.2,0,1.0,160.0,200.0,180.0,200.0,200.0,940.0,B
1,"1,90E+11",Pinhalzinho,19,M,1,3,1,1,1,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A
2,"1,90E+11",São Paulo,17,F,1,3,1,2,3,0,15567761.0,Belém,1,1,1,1,576.2,641.1,634.3,731.8,0,1.0,160.0,120.0,200.0,200.0,200.0,880.0,A
3,"1,90E+11",São Bernardo do Campo,19,M,1,3,1,2,2,0,35904958.0,São Bernardo do Campo,1,1,1,1,402.2,424.8,509.6,393.2,1,1.0,80.0,160.0,120.0,100.0,100.0,560.0,B
4,"1,90E+11",São Joaquim da Barra,37,M,2,1,1,1,1,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B

##**Reanomear registros (linha)**

In [18]:
dados1["RACA"] = dados1["RACA"].replace({0:"não_declarado", 1:"branca", 2:"preta",3:"parda",4:"amarela",5:"indígena"})
dados1["INTERNET"] = dados1["INTERNET"].replace({"A":"não", "B":"sim"})
# Outra maneira de fazer:
# Exp: dados1["INTERNET"] = dados1["INTERNET"].replace(["A","B"], ["não","sim"])

In [19]:
dados1["ESCOLA"] = dados1["ESCOLA"].replace([1,2,3,4], ["não_respondeu","pública","privada","exterior"])

In [20]:
dados1["LINGUA"] = dados1["LINGUA"].replace([0,1],["inglês","espanhol"])

In [21]:
dados1.head()

,INSCRICAO,MUNICIPIO_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,RACA,NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,IN_TREINEIRO,CO_ESCOLA,NO_MUNICIPIO_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",Santa Isabel,22,M,1,parda,1,1,não_respondeu,0,NaN,NaN,1,1,1,1,564.6,585.8,592.9,600.2,inglês,1.0,160.0,200.0,180.0,200.0,200.0,940.0,sim
1,"1,90E+11",Pinhalzinho,19,M,1,parda,1,1,não_respondeu,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,não
2,"1,90E+11",São Paulo,17,F,1,parda,1,2,privada,0,15567761.0,Belém,1,1,1,1,576.2,641.1,634.3,731.8,inglês,1.0,160.0,120.0,200.0,200.0,200.0,880.0,não
3,"1,90E+11",São Bernardo do Campo,19,M,1,parda,1,2,pública,0,35904958.0,São Bernardo do Campo,1,1,1,1,402.2,424.8,509.6,393.2,espanhol,1.0,80.0,160.0,120.0,100.0,100.0,560.0,sim
4,"1,90E+11",São Joaquim da Barra,37,M,2,branca,1,1,não_respondeu,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sim

#**Análise exploratória e Transformação dos dados**

**Análise das idades**

In [22]:
dados1["IDADE"].value_counts()

17    219313
18    147548
19     81236
16     59316
20     53009
21     37242
22     29489
23     23531
24     18851
25     15103
26     12465
15     11583
27     10367
28      8986
29      7650
30      6967
31      6331
32      5685
33      5175
34      4795
35      4340
36      4109
37      4105
38      3767
39      3299
40      3058
41      2638
42      2462
43      2307
44      2069
45      1939
46      1718
47      1578
48      1496
49      1304
50      1167
51      1014
52       933
53       841
54       727
55       652
56       530
57       497
58       388
14       355
59       325
60       254
61       236
62       176
63       144
64       139
65       115
66        81
67        72
68        53
69        43
70        40
13        29
71        25
72        17
73        16
74        13
75        10
76         8
12         6
8          6
79         4
77         3
81         3
7          3
78         3
5          2
6          2
82         2
80         2
86         1
4          1
3          1
91         1
2          1
Name: IDADE, dtype: int64

In [23]:
dados1["IDADE"].value_counts().sort_index()

2          1
3          1
4          1
5          2
6          2
7          3
8          6
12         6
13        29
14       355
15     11583
16     59316
17    219313
18    147548
19     81236
20     53009
21     37242
22     29489
23     23531
24     18851
25     15103
26     12465
27     10367
28      8986
29      7650
30      6967
31      6331
32      5685
33      5175
34      4795
35      4340
36      4109
37      4105
38      3767
39      3299
40      3058
41      2638
42      2462
43      2307
44      2069
45      1939
46      1718
47      1578
48      1496
49      1304
50      1167
51      1014
52       933
53       841
54       727
55       652
56       530
57       497
58       388
59       325
60       254
61       236
62       176
63       144
64       139
65       115
66        81
67        72
68        53
69        43
70        40
71        25
72        17
73        16
74        13
75        10
76         8
77         3
78         3
79         4
80         2
81         3
82         2
86         1
91         1
Name: IDADE, dtype: int64

**Alguns valores estranhos, idade menores que 12 e idade maiores que 80.**

In [24]:
# Inscrições abaixo de 12 anos, serão excluídas devido a alta probabilidade de erro.
menores_12 = dados1.query("IDADE < 12")["MUNICIPIO_RESIDENCIA"].value_counts()

In [25]:
menores_12

São Paulo                 5
Tambaú                    1
Ribeirão Preto            1
Bálsamo                   1
São Bernardo do Campo     1
Embu das Artes            1
Queiroz                   1
Santana de Parnaíba       1
Vargem Grande Paulista    1
Auriflama                 1
Araçatuba                 1
Campinas                  1
Name: MUNICIPIO_RESIDENCIA, dtype: int64

In [26]:
dados_maior_11 = dados1.loc[dados1.IDADE > 11]

In [27]:
dados_maior_11.head()

,INSCRICAO,MUNICIPIO_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,RACA,NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,IN_TREINEIRO,CO_ESCOLA,NO_MUNICIPIO_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",Santa Isabel,22,M,1,parda,1,1,não_respondeu,0,NaN,NaN,1,1,1,1,564.6,585.8,592.9,600.2,inglês,1.0,160.0,200.0,180.0,200.0,200.0,940.0,sim
1,"1,90E+11",Pinhalzinho,19,M,1,parda,1,1,não_respondeu,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,não
2,"1,90E+11",São Paulo,17,F,1,parda,1,2,privada,0,15567761.0,Belém,1,1,1,1,576.2,641.1,634.3,731.8,inglês,1.0,160.0,120.0,200.0,200.0,200.0,880.0,não
3,"1,90E+11",São Bernardo do Campo,19,M,1,parda,1,2,pública,0,35904958.0,São Bernardo do Campo,1,1,1,1,402.2,424.8,509.6,393.2,espanhol,1.0,80.0,160.0,120.0,100.0,100.0,560.0,sim
4,"1,90E+11",São Joaquim da Barra,37,M,2,branca,1,1,não_respondeu,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sim

In [28]:
dados_maior_11["IDADE"].value_counts().sort_index()

12         6
13        29
14       355
15     11583
16     59316
17    219313
18    147548
19     81236
20     53009
21     37242
22     29489
23     23531
24     18851
25     15103
26     12465
27     10367
28      8986
29      7650
30      6967
31      6331
32      5685
33      5175
34      4795
35      4340
36      4109
37      4105
38      3767
39      3299
40      3058
41      2638
42      2462
43      2307
44      2069
45      1939
46      1718
47      1578
48      1496
49      1304
50      1167
51      1014
52       933
53       841
54       727
55       652
56       530
57       497
58       388
59       325
60       254
61       236
62       176
63       144
64       139
65       115
66        81
67        72
68        53
69        43
70        40
71        25
72        17
73        16
74        13
75        10
76         8
77         3
78         3
79         4
80         2
81         3
82         2
86         1
91         1
Name: IDADE, dtype: int64

**Treineiro**

In [29]:
dados_maior_11.query("IN_TREINEIRO == 1")["IN_TREINEIRO"].value_counts()

1    93988
Name: IN_TREINEIRO, dtype: int64

In [30]:
treineiros = dados_maior_11.loc[dados_maior_11.IN_TREINEIRO == 1]

In [31]:
treineiros.head()

,INSCRICAO,MUNICIPIO_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,RACA,NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,IN_TREINEIRO,CO_ESCOLA,NO_MUNICIPIO_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
20,"1,90E+11",Santos,15,F,1,parda,1,3,não_respondeu,1,NaN,NaN,1,1,1,1,455.4,506.7,480.4,573.2,inglês,1.0,140.0,120.0,120.0,100.0,80.0,560.0,sim
21,"1,90E+11",Panorama,16,F,1,parda,1,3,não_respondeu,1,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,não
106,"1,90E+11",São Paulo,16,F,1,branca,1,3,não_respondeu,1,NaN,NaN,1,1,1,1,424.5,517.7,489.6,532.6,inglês,1.0,120.0,120.0,120.0,100.0,80.0,540.0,sim
109,"1,90E+11",Águas de Lindóia,16,M,1,branca,1,3,não_respondeu,1,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sim
159,"1,90E+11",Águas de Lindóia,15,M,1,branca,1,3,não_respondeu,1,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,inglês,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sim

In [32]:
treineiros.to_csv("treineiros_enem_2019_sp.csv", encoding = "iso-8859-1", index = False)

In [33]:
# Separação entre vestibulando e treineiros
vestibulandos = dados_maior_11.loc[dados_maior_11.IN_TREINEIRO == 0]

In [34]:
vestibulandos.head()

,INSCRICAO,MUNICIPIO_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,RACA,NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,IN_TREINEIRO,CO_ESCOLA,NO_MUNICIPIO_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",Santa Isabel,22,M,1,parda,1,1,não_respondeu,0,NaN,NaN,1,1,1,1,564.6,585.8,592.9,600.2,inglês,1.0,160.0,200.0,180.0,200.0,200.0,940.0,sim
1,"1,90E+11",Pinhalzinho,19,M,1,parda,1,1,não_respondeu,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,não
2,"1,90E+11",São Paulo,17,F,1,parda,1,2,privada,0,15567761.0,Belém,1,1,1,1,576.2,641.1,634.3,731.8,inglês,1.0,160.0,120.0,200.0,200.0,200.0,880.0,não
3,"1,90E+11",São Bernardo do Campo,19,M,1,parda,1,2,pública,0,35904958.0,São Bernardo do Campo,1,1,1,1,402.2,424.8,509.6,393.2,espanhol,1.0,80.0,160.0,120.0,100.0,100.0,560.0,sim
4,"1,90E+11",São Joaquim da Barra,37,M,2,branca,1,1,não_respondeu,0,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,espanhol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sim

In [35]:
vestibulandos.shape

(719768, 29)

**Análise das presenças**

In [36]:
vestibulandos["TP_PRESENCA_CN"].value_counts()

1    500805
0    218693
2       270
Name: TP_PRESENCA_CN, dtype: int64

In [37]:
vestibulandos["TP_PRESENCA_CH"].value_counts()

1    533142
0    185969
2       657
Name: TP_PRESENCA_CH, dtype: int64

In [38]:
vestibulandos["TP_PRESENCA_LC"].value_counts()

1    533142
0    185969
2       657
Name: TP_PRESENCA_LC, dtype: int64

In [39]:
vestibulandos["TP_PRESENCA_MT"].value_counts()

1    500805
0    218693
2       270
Name: TP_PRESENCA_MT, dtype: int64

###RESULMO PRESENÇA NAS PROVAS

CIÊNCIAS DA NATUREZA:
500805 Presentes,
218693 Faltaram e
270 Eliminados

CIÊNCIAS HUMANAS:
533142 Presentes,
185969 Faltaram e
657 Eliminados

LINGUAGEM E CÓDIGOS:
533142 Presentes,
185969 Faltaram e
657 Eliminados

MATEMÁTICAT:
500805 Presentes,
218693 Faltaram e
270 Eliminados

In [40]:
vestibulandos["TP_STATUS_REDACAO"].value_counts().sort_index()

1.0    519763
2.0       913
3.0      1417
4.0      5513
6.0      3626
7.0       543
8.0       828
9.0       539
Name: TP_STATUS_REDACAO, dtype: int64

**valores ausentes**

In [41]:
vestibulandos["IDADE"].isnull().sum()

0

In [42]:
provas = ["NOTA_REDACAO","NOTA_CN","NOTA_MT","NOTA_LC","NOTA_CH"]

In [43]:
# Registros NAN nas notas
vestibulandos [provas].isnull().sum()

NOTA_REDACAO    186626
NOTA_CN         218963
NOTA_MT         218963
NOTA_LC         186626
NOTA_CH         186626
dtype: int64

In [44]:
vestibulandos_classificados = vestibulandos.loc[vestibulandos.TP_PRESENCA_CH == 1]
vestibulandos_classificados = vestibulandos_classificados.loc[vestibulandos_classificados.TP_PRESENCA_MT == 1]

In [45]:
vestibulandos_classificados["TP_PRESENCA_MT"].value_counts()

1    499940
Name: TP_PRESENCA_MT, dtype: int64

In [46]:
vestibulandos_classificados["TP_PRESENCA_CH"].value_counts()

1    499940
Name: TP_PRESENCA_CH, dtype: int64

In [47]:
vestibulandos_classificados["TP_PRESENCA_LC"].value_counts()

1    499940
Name: TP_PRESENCA_LC, dtype: int64

In [48]:
vestibulandos_classificados["TP_PRESENCA_CN"].value_counts()

1    499940
Name: TP_PRESENCA_CN, dtype: int64

In [49]:
vestibulandos_classificados[provas].isnull().sum()

NOTA_REDACAO    0
NOTA_CN         0
NOTA_MT         0
NOTA_LC         0
NOTA_CH         0
dtype: int64

**Notas zeradas na redação**

In [50]:
vestibulandos_classificados.query("NOTA_REDACAO == 0")["NOTA_REDACAO"].value_counts()

0.0    9181
Name: NOTA_REDACAO, dtype: int64

In [51]:
vestibulandos_classificados.query("COMP1 == 0")["COMP1"].value_counts()

0.0    9188
Name: COMP1, dtype: int64

In [52]:
vestibulandos_classificados.query("COMP2 == 0")["COMP2"].value_counts()

0.0    9181
Name: COMP2, dtype: int64

In [53]:
vestibulandos_classificados.query("COMP3 == 0")["COMP3"].value_counts()

0.0    9197
Name: COMP3, dtype: int64

In [54]:
vestibulandos_classificados.query("COMP4 == 0")["COMP4"].value_counts()

0.0    9194
Name: COMP4, dtype: int64

In [55]:
vestibulandos_classificados.query("COMP5 == 0")["COMP5"].value_counts()

0.0    73330
Name: COMP5, dtype: int64

#**Resulmo notas 0 na redação**

NOTA_REDAÇÂo: 9181 notas zeradas;

COMP1: 9188 notas zeradas nesse componente;

COMP2: 9181 notas zeradas nesse componente;

COMP3: 9197 notas zeradas nesse componente;

COMP4: 9188 notas zeradas nesse componente;

COMP5: 73330 notas zeradas nesse componente;

In [56]:
vestibulandos_classificados.query("NOTA_CN == 0")["NOTA_CN"].value_counts()

0.0    36
Name: NOTA_CN, dtype: int64

In [57]:
vestibulandos_classificados.query("NOTA_MT == 0")["NOTA_MT"].value_counts()

0.0    56
Name: NOTA_MT, dtype: int64

In [58]:
vestibulandos_classificados.query("NOTA_CH == 0")["NOTA_CH"].value_counts()

0.0    343
Name: NOTA_CH, dtype: int64

In [59]:
vestibulandos_classificados.query("NOTA_LC == 0")["NOTA_LC"].value_counts()

0.0    135
Name: NOTA_LC, dtype: int64

##Notas zero dos inscritos concorrentes ao vestibular:

Ciências da Natureza: 36

Ciências Humanas:343

Linguagens e Códigos: 135

Matemática: 56

Redação: 9181

In [60]:
vestibulandos_classificados.head()

,INSCRICAO,MUNICIPIO_RESIDENCIA,IDADE,SEXO,ESTADO_CIVIL,RACA,NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,IN_TREINEIRO,CO_ESCOLA,NO_MUNICIPIO_ESC,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NOTA_CN,NOTA_CH,NOTA_LC,NOTA_MT,LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",Santa Isabel,22,M,1,parda,1,1,não_respondeu,0,NaN,NaN,1,1,1,1,564.6,585.8,592.9,600.2,inglês,1.0,160.0,200.0,180.0,200.0,200.0,940.0,sim
2,"1,90E+11",São Paulo,17,F,1,parda,1,2,privada,0,15567761.0,Belém,1,1,1,1,576.2,641.1,634.3,731.8,inglês,1.0,160.0,120.0,200.0,200.0,200.0,880.0,não
3,"1,90E+11",São Bernardo do Campo,19,M,1,parda,1,2,pública,0,35904958.0,São Bernardo do Campo,1,1,1,1,402.2,424.8,509.6,393.2,espanhol,1.0,80.0,160.0,120.0,100.0,100.0,560.0,sim
5,"1,90E+11",Embu-Guaçu,17,F,1,parda,1,2,pública,0,NaN,NaN,1,1,1,1,399.6,426.8,487.2,419.2,inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,sim
8,"1,90E+11",Guarulhos,23,F,1,branca,1,1,não_respondeu,0,NaN,NaN,1,1,1,1,625.7,646.5,629.3,796.1,inglês,1.0,160.0,200.0,180.0,180.0,160.0,880.0,sim

In [63]:
vestibulandos_classificados = vestibulandos_classificados.drop(columns=["IN_TREINEIRO"],)

In [64]:
vestibulandos_classificados.shape

(499940, 28)

#**Referências e links úteis**
**Referências Bibliográficas**

LARSON, Ron. **Estatística Aplicada.** São Paulo: Pearson Prentice Hall, 2010.

COSTA NETO, Pedro Luiz de Oliveira. **Estatística.** São Paulo: Bluncher, 2002.

MORETTIN, Luiz Gonzaga. **Estatística Básica: probabilidade e inferência.** São Paulo: Pearson Prentice Hall, 2010.



**LINKS ÚTEIS:**

**Site INEP dos microdados do ENEM:**

https://www.gov.br/inep/pt-br/acesso-a-informacao/dados-abertos/microdados/enem

**Estatística:**

https://www.udemy.com/course/estatistica-com-linguagem-r/?referralCode=0DBFC727FE8574D5BCE8

**Graus de liberdade:**

https://pt.khanacademy.org/math/ap-statistics/summarizing-quantitative-data-ap/more-standard-deviation/v/another-simulation-giving-evidence-that-n-1-gives-us-an-unbiased-estimate-of-variance

**Teste de Normalidade:**

https://www.inf.ufsc.br/~vera.carmo/Testes_de_Hipoteses/Testes_aderencia.pdf

**Bibliotecas Python**

https://docs.python.org/pt-br/3/library/

https://pandas.pydata.org/docs/

https://docs.scipy.org/

https://www.anaconda.com/products/individual

**Gráficos**

https://seaborn.pydata.org/index.html

https://plotly.com/python/reference/#layout